name: DGAT2_final_GitHub
channels:
  - pytorch
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - gzip=1.14
  - jupyterlab=4.4.9
  - jupyter
  - matplotlib=3.10.6
  - matplotlib-inline=0.1.7
  - numpy=1.26.4
  - pickleshare=0.7.5
  - python=3.12.11
  - pytorch=2.2.2
  - pandas=2.3.3
  - scikit-learn=1.7.2
